# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smart-Home_IoT-GP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart-Home_IoT-GP
    pod 'Alamofire', '~> 4.5'
    pod 'CocoaMQTT'  
    pod 'SkyFloatingLabelTextField', '~> 3.0'

end
